version: 2

# Используем последнюю стабильную LTS-версию Ubuntu
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  jobs:
    pre_build:
      - echo "Installing uv..."
      - pip install uv
      - echo "Installing dependencies with uv..."
      - uv pip install -r pyproject.toml --group=docs

python:
  install: []

mkdocs:
  configuration: mkdocs.yml
